
name: jupyterlab_documentation
channels:
  - conda-forge
dependencies:
- python=3.8
- sphinx>=1.8
- sphinx-copybutton
- sphinx_rtd_theme
- pytest
- pip
- nodejs
- requests_cache
- jsx-lexer
- myst-parser
- pytest-check-links
